#!/usr/bin/env bash
# setup-credentials.sh
# Interactive wizard to populate ~/.secrets with API keys and tokens.
# Idempotent — re-running updates only the values you change.
set -euo pipefail

SECRETS_FILE="$HOME/.secrets"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Credential Setup Wizard"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Secrets are saved to ~/.secrets (chmod 600)."
echo "  This file is gitignored and never committed."
echo "  Press Enter to keep the current value for any field."
echo ""

# Source existing secrets so we can show [already set]
if [[ -f "$SECRETS_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$SECRETS_FILE" 2>/dev/null || true
fi

# ── Prompt helper ────────────────────────────────────────────────────────────
# Usage: result=$(prompt_secret VAR_NAME "Display label")
prompt_secret() {
    local var_name="$1"
    local label="$2"
    local current="${!var_name:-}"
    local new_val=""

    if [[ -n "$current" ]]; then
        read -rp "  $label [already set — Enter to keep]: " new_val
    else
        read -rsp "  $label: " new_val
        echo ""
    fi

    if [[ -n "$new_val" ]]; then
        echo "$new_val"
    else
        echo "$current"
    fi
}

# ── Anthropic ────────────────────────────────────────────────────────────────
echo "── Anthropic ────────────────────────────────────────────────────────────"
NEW_ANTHROPIC_API_KEY=$(prompt_secret "ANTHROPIC_API_KEY" "API Key (sk-ant-...)")

# ── Oracle Cloud ─────────────────────────────────────────────────────────────
echo ""
echo "── Oracle Cloud (OCI) ───────────────────────────────────────────────────"
NEW_OCIR_TOKEN=$(prompt_secret "OCIR_TOKEN"     "Registry Token")
NEW_OCIR_REGION=$(prompt_secret "OCIR_REGION"   "Region (e.g. iad, phx, lhr)")
NEW_OCIR_NAMESPACE=$(prompt_secret "OCIR_NAMESPACE" "Tenancy Namespace")

# ── DigitalOcean ─────────────────────────────────────────────────────────────
echo ""
echo "── DigitalOcean ─────────────────────────────────────────────────────────"
NEW_DIGITAL_OCEAN_TOKEN=$(prompt_secret "DIGITAL_OCEAN_TOKEN" "Personal Access Token (dop_...)")

# ── Databases ────────────────────────────────────────────────────────────────
echo ""
echo "── Databases ────────────────────────────────────────────────────────────"
NEW_DB_PASSWORD=$(prompt_secret "DB_PASSWORD" "Default DB Password")

# ── Write ~/.secrets ─────────────────────────────────────────────────────────
cat > "$SECRETS_FILE" << EOF
# Developer Environment — Secrets
# Generated by setup-credentials.sh on $(date)
# chmod 600 — NEVER commit this file.

# ── Anthropic ────────────────────────────────────────────────────────────────
export ANTHROPIC_API_KEY="$NEW_ANTHROPIC_API_KEY"

# ── Oracle Cloud (OCI) ───────────────────────────────────────────────────────
export OCIR_TOKEN="$NEW_OCIR_TOKEN"
export OCIR_REGION="$NEW_OCIR_REGION"
export OCIR_NAMESPACE="$NEW_OCIR_NAMESPACE"

# ── DigitalOcean ─────────────────────────────────────────────────────────────
export DIGITAL_OCEAN_TOKEN="$NEW_DIGITAL_OCEAN_TOKEN"

# ── Databases ────────────────────────────────────────────────────────────────
export DB_PASSWORD="$NEW_DB_PASSWORD"
EOF

chmod 600 "$SECRETS_FILE"
echo ""
echo "  ~/.secrets written ✓"

# ── GitHub CLI ───────────────────────────────────────────────────────────────
echo ""
echo "── GitHub CLI ───────────────────────────────────────────────────────────"
if command -v gh &>/dev/null; then
    if gh auth status &>/dev/null 2>&1; then
        echo "  GitHub CLI already authenticated ✓"
    else
        echo "  Running: gh auth login"
        gh auth login
    fi
else
    echo "  gh not installed — run: brew install gh"
fi

# ── doctl ────────────────────────────────────────────────────────────────────
echo ""
echo "── DigitalOcean CLI (doctl) ─────────────────────────────────────────────"
if command -v doctl &>/dev/null; then
    if doctl account get &>/dev/null 2>&1; then
        echo "  doctl already authenticated ✓"
    else
        echo "  Authenticating doctl with your token..."
        doctl auth init --access-token "$NEW_DIGITAL_OCEAN_TOKEN" 2>/dev/null || \
            echo "  Could not auto-auth doctl — run: doctl auth init"
    fi
else
    echo "  doctl not installed — run: brew install doctl"
fi

# ── Claude Code ──────────────────────────────────────────────────────────────
echo ""
echo "── Claude Code ──────────────────────────────────────────────────────────"
if command -v claude &>/dev/null; then
    echo "  Claude Code already installed ✓"
else
    echo "  Installing Claude Code..."
    npm install -g @anthropic-ai/claude-code 2>/dev/null || \
        echo "  Could not auto-install — run: npm install -g @anthropic-ai/claude-code"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  All done!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Reload secrets:  source ~/.secrets"
echo "  Or open a new terminal window."
echo ""
